// Package models contains the types for schema ''.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
)

// CuptiActivityKindConcurrentKernel represents a row from 'CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL'.
type CuptiActivityKindConcurrentKernel struct {
	ID                              sql.NullInt64 `json:"_id_"`                            // _id_
	Cacheconfig                     []byte        `json:"cacheConfig"`                     // cacheConfig
	Sharedmemoryconfig              int           `json:"sharedMemoryConfig"`              // sharedMemoryConfig
	Registersperthread              int           `json:"registersPerThread"`              // registersPerThread
	Partitionedglobalcacherequested int           `json:"partitionedGlobalCacheRequested"` // partitionedGlobalCacheRequested
	Partitionedglobalcacheexecuted  int           `json:"partitionedGlobalCacheExecuted"`  // partitionedGlobalCacheExecuted
	Start                           int           `json:"start"`                           // start
	End                             int           `json:"end"`                             // end
	Completed                       int           `json:"completed"`                       // completed
	Deviceid                        int           `json:"deviceId"`                        // deviceId
	Contextid                       int           `json:"contextId"`                       // contextId
	Streamid                        int           `json:"streamId"`                        // streamId
	Gridx                           int           `json:"gridX"`                           // gridX
	Gridy                           int           `json:"gridY"`                           // gridY
	Gridz                           int           `json:"gridZ"`                           // gridZ
	Blockx                          int           `json:"blockX"`                          // blockX
	Blocky                          int           `json:"blockY"`                          // blockY
	Blockz                          int           `json:"blockZ"`                          // blockZ
	Staticsharedmemory              int           `json:"staticSharedMemory"`              // staticSharedMemory
	Dynamicsharedmemory             int           `json:"dynamicSharedMemory"`             // dynamicSharedMemory
	Localmemoryperthread            int           `json:"localMemoryPerThread"`            // localMemoryPerThread
	Localmemorytotal                int           `json:"localMemoryTotal"`                // localMemoryTotal
	Correlationid                   int           `json:"correlationId"`                   // correlationId
	Gridid                          int           `json:"gridId"`                          // gridId
	Name                            int           `json:"name"`                            // name
	Queued                          int           `json:"queued"`                          // queued
	Submitted                       int           `json:"submitted"`                       // submitted
	Launchtype                      int           `json:"launchType"`                      // launchType
	Issharedmemorycarveoutrequested int           `json:"isSharedMemoryCarveoutRequested"` // isSharedMemoryCarveoutRequested
	Sharedmemorycarveoutrequested   int           `json:"sharedMemoryCarveoutRequested"`   // sharedMemoryCarveoutRequested

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the CuptiActivityKindConcurrentKernel exists in the database.
func (cakck *CuptiActivityKindConcurrentKernel) Exists() bool {
	return cakck._exists
}

// Deleted provides information if the CuptiActivityKindConcurrentKernel has been deleted from the database.
func (cakck *CuptiActivityKindConcurrentKernel) Deleted() bool {
	return cakck._deleted
}

// Insert inserts the CuptiActivityKindConcurrentKernel to the database.
func (cakck *CuptiActivityKindConcurrentKernel) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if cakck._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL (` +
		`cacheConfig, sharedMemoryConfig, registersPerThread, partitionedGlobalCacheRequested, partitionedGlobalCacheExecuted, start, end, completed, deviceId, contextId, streamId, gridX, gridY, gridZ, blockX, blockY, blockZ, staticSharedMemory, dynamicSharedMemory, localMemoryPerThread, localMemoryTotal, correlationId, gridId, name, queued, submitted, launchType, isSharedMemoryCarveoutRequested, sharedMemoryCarveoutRequested` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, cakck.Cacheconfig, cakck.Sharedmemoryconfig, cakck.Registersperthread, cakck.Partitionedglobalcacherequested, cakck.Partitionedglobalcacheexecuted, cakck.Start, cakck.End, cakck.Completed, cakck.Deviceid, cakck.Contextid, cakck.Streamid, cakck.Gridx, cakck.Gridy, cakck.Gridz, cakck.Blockx, cakck.Blocky, cakck.Blockz, cakck.Staticsharedmemory, cakck.Dynamicsharedmemory, cakck.Localmemoryperthread, cakck.Localmemorytotal, cakck.Correlationid, cakck.Gridid, cakck.Name, cakck.Queued, cakck.Submitted, cakck.Launchtype, cakck.Issharedmemorycarveoutrequested, cakck.Sharedmemorycarveoutrequested)
	res, err := db.Exec(sqlstr, cakck.Cacheconfig, cakck.Sharedmemoryconfig, cakck.Registersperthread, cakck.Partitionedglobalcacherequested, cakck.Partitionedglobalcacheexecuted, cakck.Start, cakck.End, cakck.Completed, cakck.Deviceid, cakck.Contextid, cakck.Streamid, cakck.Gridx, cakck.Gridy, cakck.Gridz, cakck.Blockx, cakck.Blocky, cakck.Blockz, cakck.Staticsharedmemory, cakck.Dynamicsharedmemory, cakck.Localmemoryperthread, cakck.Localmemorytotal, cakck.Correlationid, cakck.Gridid, cakck.Name, cakck.Queued, cakck.Submitted, cakck.Launchtype, cakck.Issharedmemorycarveoutrequested, cakck.Sharedmemorycarveoutrequested)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	cakck.ID = sql.NullInt64(id)
	cakck._exists = true

	return nil
}

// Update updates the CuptiActivityKindConcurrentKernel in the database.
func (cakck *CuptiActivityKindConcurrentKernel) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cakck._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if cakck._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL SET ` +
		`cacheConfig = ?, sharedMemoryConfig = ?, registersPerThread = ?, partitionedGlobalCacheRequested = ?, partitionedGlobalCacheExecuted = ?, start = ?, end = ?, completed = ?, deviceId = ?, contextId = ?, streamId = ?, gridX = ?, gridY = ?, gridZ = ?, blockX = ?, blockY = ?, blockZ = ?, staticSharedMemory = ?, dynamicSharedMemory = ?, localMemoryPerThread = ?, localMemoryTotal = ?, correlationId = ?, gridId = ?, name = ?, queued = ?, submitted = ?, launchType = ?, isSharedMemoryCarveoutRequested = ?, sharedMemoryCarveoutRequested = ?` +
		` WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cakck.Cacheconfig, cakck.Sharedmemoryconfig, cakck.Registersperthread, cakck.Partitionedglobalcacherequested, cakck.Partitionedglobalcacheexecuted, cakck.Start, cakck.End, cakck.Completed, cakck.Deviceid, cakck.Contextid, cakck.Streamid, cakck.Gridx, cakck.Gridy, cakck.Gridz, cakck.Blockx, cakck.Blocky, cakck.Blockz, cakck.Staticsharedmemory, cakck.Dynamicsharedmemory, cakck.Localmemoryperthread, cakck.Localmemorytotal, cakck.Correlationid, cakck.Gridid, cakck.Name, cakck.Queued, cakck.Submitted, cakck.Launchtype, cakck.Issharedmemorycarveoutrequested, cakck.Sharedmemorycarveoutrequested, cakck.ID)
	_, err = db.Exec(sqlstr, cakck.Cacheconfig, cakck.Sharedmemoryconfig, cakck.Registersperthread, cakck.Partitionedglobalcacherequested, cakck.Partitionedglobalcacheexecuted, cakck.Start, cakck.End, cakck.Completed, cakck.Deviceid, cakck.Contextid, cakck.Streamid, cakck.Gridx, cakck.Gridy, cakck.Gridz, cakck.Blockx, cakck.Blocky, cakck.Blockz, cakck.Staticsharedmemory, cakck.Dynamicsharedmemory, cakck.Localmemoryperthread, cakck.Localmemorytotal, cakck.Correlationid, cakck.Gridid, cakck.Name, cakck.Queued, cakck.Submitted, cakck.Launchtype, cakck.Issharedmemorycarveoutrequested, cakck.Sharedmemorycarveoutrequested, cakck.ID)
	return err
}

// Save saves the CuptiActivityKindConcurrentKernel to the database.
func (cakck *CuptiActivityKindConcurrentKernel) Save(db XODB) error {
	if cakck.Exists() {
		return cakck.Update(db)
	}

	return cakck.Insert(db)
}

// Delete deletes the CuptiActivityKindConcurrentKernel from the database.
func (cakck *CuptiActivityKindConcurrentKernel) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cakck._exists {
		return nil
	}

	// if deleted, bail
	if cakck._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cakck.ID)
	_, err = db.Exec(sqlstr, cakck.ID)
	if err != nil {
		return err
	}

	// set deleted
	cakck._deleted = true

	return nil
}

// CuptiActivityKindConcurrentKernelByID retrieves a row from 'CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL' as a CuptiActivityKindConcurrentKernel.
//
// Generated from index 'CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL__id__pkey'.
func CuptiActivityKindConcurrentKernelByID(db XODB, id sql.NullInt64) (*CuptiActivityKindConcurrentKernel, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, cacheConfig, sharedMemoryConfig, registersPerThread, partitionedGlobalCacheRequested, partitionedGlobalCacheExecuted, start, end, completed, deviceId, contextId, streamId, gridX, gridY, gridZ, blockX, blockY, blockZ, staticSharedMemory, dynamicSharedMemory, localMemoryPerThread, localMemoryTotal, correlationId, gridId, name, queued, submitted, launchType, isSharedMemoryCarveoutRequested, sharedMemoryCarveoutRequested ` +
		`FROM CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL ` +
		`WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, id)
	cakck := CuptiActivityKindConcurrentKernel{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&cakck.ID, &cakck.Cacheconfig, &cakck.Sharedmemoryconfig, &cakck.Registersperthread, &cakck.Partitionedglobalcacherequested, &cakck.Partitionedglobalcacheexecuted, &cakck.Start, &cakck.End, &cakck.Completed, &cakck.Deviceid, &cakck.Contextid, &cakck.Streamid, &cakck.Gridx, &cakck.Gridy, &cakck.Gridz, &cakck.Blockx, &cakck.Blocky, &cakck.Blockz, &cakck.Staticsharedmemory, &cakck.Dynamicsharedmemory, &cakck.Localmemoryperthread, &cakck.Localmemorytotal, &cakck.Correlationid, &cakck.Gridid, &cakck.Name, &cakck.Queued, &cakck.Submitted, &cakck.Launchtype, &cakck.Issharedmemorycarveoutrequested, &cakck.Sharedmemorycarveoutrequested)
	if err != nil {
		return nil, err
	}

	return &cakck, nil
}

// CuptiActivityKindConcurrentKernelsByCorrelationid retrieves a row from 'CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL' as a CuptiActivityKindConcurrentKernel.
//
// Generated from index 'INDEX_CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL'.
func CuptiActivityKindConcurrentKernelsByCorrelationid(db XODB, correlationid int) ([]*CuptiActivityKindConcurrentKernel, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, cacheConfig, sharedMemoryConfig, registersPerThread, partitionedGlobalCacheRequested, partitionedGlobalCacheExecuted, start, end, completed, deviceId, contextId, streamId, gridX, gridY, gridZ, blockX, blockY, blockZ, staticSharedMemory, dynamicSharedMemory, localMemoryPerThread, localMemoryTotal, correlationId, gridId, name, queued, submitted, launchType, isSharedMemoryCarveoutRequested, sharedMemoryCarveoutRequested ` +
		`FROM CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL ` +
		`WHERE correlationId = ?`

	// run query
	XOLog(sqlstr, correlationid)
	q, err := db.Query(sqlstr, correlationid)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*CuptiActivityKindConcurrentKernel{}
	for q.Next() {
		cakck := CuptiActivityKindConcurrentKernel{
			_exists: true,
		}

		// scan
		err = q.Scan(&cakck.ID, &cakck.Cacheconfig, &cakck.Sharedmemoryconfig, &cakck.Registersperthread, &cakck.Partitionedglobalcacherequested, &cakck.Partitionedglobalcacheexecuted, &cakck.Start, &cakck.End, &cakck.Completed, &cakck.Deviceid, &cakck.Contextid, &cakck.Streamid, &cakck.Gridx, &cakck.Gridy, &cakck.Gridz, &cakck.Blockx, &cakck.Blocky, &cakck.Blockz, &cakck.Staticsharedmemory, &cakck.Dynamicsharedmemory, &cakck.Localmemoryperthread, &cakck.Localmemorytotal, &cakck.Correlationid, &cakck.Gridid, &cakck.Name, &cakck.Queued, &cakck.Submitted, &cakck.Launchtype, &cakck.Issharedmemorycarveoutrequested, &cakck.Sharedmemorycarveoutrequested)
		if err != nil {
			return nil, err
		}

		res = append(res, &cakck)
	}

	return res, nil
}
