// Package models contains the types for schema ''.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
)

// CuptiActivityKindInstantaneousEventInstance represents a row from 'CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE'.
type CuptiActivityKindInstantaneousEventInstance struct {
	ID        sql.NullInt64 `json:"_id_"`      // _id_
	ID        int           `json:"id"`        // id
	Value     int           `json:"value"`     // value
	Timestamp int           `json:"timestamp"` // timestamp
	Deviceid  int           `json:"deviceId"`  // deviceId
	Instance  int           `json:"instance"`  // instance

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the CuptiActivityKindInstantaneousEventInstance exists in the database.
func (cakiei *CuptiActivityKindInstantaneousEventInstance) Exists() bool {
	return cakiei._exists
}

// Deleted provides information if the CuptiActivityKindInstantaneousEventInstance has been deleted from the database.
func (cakiei *CuptiActivityKindInstantaneousEventInstance) Deleted() bool {
	return cakiei._deleted
}

// Insert inserts the CuptiActivityKindInstantaneousEventInstance to the database.
func (cakiei *CuptiActivityKindInstantaneousEventInstance) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if cakiei._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE (` +
		`value, timestamp, deviceId, instance` +
		`) VALUES (` +
		`?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, cakiei.Value, cakiei.Timestamp, cakiei.Deviceid, cakiei.Instance)
	res, err := db.Exec(sqlstr, cakiei.Value, cakiei.Timestamp, cakiei.Deviceid, cakiei.Instance)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	cakiei.ID = sql.NullInt64(id)
	cakiei._exists = true

	return nil
}

// Update updates the CuptiActivityKindInstantaneousEventInstance in the database.
func (cakiei *CuptiActivityKindInstantaneousEventInstance) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cakiei._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if cakiei._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE SET ` +
		`value = ?, timestamp = ?, deviceId = ?, instance = ?` +
		` WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cakiei.Value, cakiei.Timestamp, cakiei.Deviceid, cakiei.Instance, cakiei.ID)
	_, err = db.Exec(sqlstr, cakiei.Value, cakiei.Timestamp, cakiei.Deviceid, cakiei.Instance, cakiei.ID)
	return err
}

// Save saves the CuptiActivityKindInstantaneousEventInstance to the database.
func (cakiei *CuptiActivityKindInstantaneousEventInstance) Save(db XODB) error {
	if cakiei.Exists() {
		return cakiei.Update(db)
	}

	return cakiei.Insert(db)
}

// Delete deletes the CuptiActivityKindInstantaneousEventInstance from the database.
func (cakiei *CuptiActivityKindInstantaneousEventInstance) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cakiei._exists {
		return nil
	}

	// if deleted, bail
	if cakiei._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cakiei.ID)
	_, err = db.Exec(sqlstr, cakiei.ID)
	if err != nil {
		return err
	}

	// set deleted
	cakiei._deleted = true

	return nil
}

// CuptiActivityKindInstantaneousEventInstanceByID retrieves a row from 'CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE' as a CuptiActivityKindInstantaneousEventInstance.
//
// Generated from index 'CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE__id__pkey'.
func CuptiActivityKindInstantaneousEventInstanceByID(db XODB, id sql.NullInt64) (*CuptiActivityKindInstantaneousEventInstance, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, id, value, timestamp, deviceId, instance ` +
		`FROM CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE ` +
		`WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, id)
	cakiei := CuptiActivityKindInstantaneousEventInstance{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&cakiei.ID, &cakiei.ID, &cakiei.Value, &cakiei.Timestamp, &cakiei.Deviceid, &cakiei.Instance)
	if err != nil {
		return nil, err
	}

	return &cakiei, nil
}

// CuptiActivityKindInstantaneousEventInstancesByTimestamp retrieves a row from 'CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE' as a CuptiActivityKindInstantaneousEventInstance.
//
// Generated from index 'INDEX_CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE'.
func CuptiActivityKindInstantaneousEventInstancesByTimestamp(db XODB, timestamp int) ([]*CuptiActivityKindInstantaneousEventInstance, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, id, value, timestamp, deviceId, instance ` +
		`FROM CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE ` +
		`WHERE timestamp = ?`

	// run query
	XOLog(sqlstr, timestamp)
	q, err := db.Query(sqlstr, timestamp)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*CuptiActivityKindInstantaneousEventInstance{}
	for q.Next() {
		cakiei := CuptiActivityKindInstantaneousEventInstance{
			_exists: true,
		}

		// scan
		err = q.Scan(&cakiei.ID, &cakiei.ID, &cakiei.Value, &cakiei.Timestamp, &cakiei.Deviceid, &cakiei.Instance)
		if err != nil {
			return nil, err
		}

		res = append(res, &cakiei)
	}

	return res, nil
}
