// Package models contains the types for schema ''.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
)

// CuptiActivityKindMetric represents a row from 'CUPTI_ACTIVITY_KIND_METRIC'.
type CuptiActivityKindMetric struct {
	ID            sql.NullInt64 `json:"_id_"`          // _id_
	ID            int           `json:"id"`            // id
	Value         []byte        `json:"value"`         // value
	Correlationid int           `json:"correlationId"` // correlationId
	Flags         int           `json:"flags"`         // flags

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the CuptiActivityKindMetric exists in the database.
func (cakm *CuptiActivityKindMetric) Exists() bool {
	return cakm._exists
}

// Deleted provides information if the CuptiActivityKindMetric has been deleted from the database.
func (cakm *CuptiActivityKindMetric) Deleted() bool {
	return cakm._deleted
}

// Insert inserts the CuptiActivityKindMetric to the database.
func (cakm *CuptiActivityKindMetric) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if cakm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO CUPTI_ACTIVITY_KIND_METRIC (` +
		`value, correlationId, flags` +
		`) VALUES (` +
		`?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, cakm.Value, cakm.Correlationid, cakm.Flags)
	res, err := db.Exec(sqlstr, cakm.Value, cakm.Correlationid, cakm.Flags)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	cakm.ID = sql.NullInt64(id)
	cakm._exists = true

	return nil
}

// Update updates the CuptiActivityKindMetric in the database.
func (cakm *CuptiActivityKindMetric) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cakm._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if cakm._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE CUPTI_ACTIVITY_KIND_METRIC SET ` +
		`value = ?, correlationId = ?, flags = ?` +
		` WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cakm.Value, cakm.Correlationid, cakm.Flags, cakm.ID)
	_, err = db.Exec(sqlstr, cakm.Value, cakm.Correlationid, cakm.Flags, cakm.ID)
	return err
}

// Save saves the CuptiActivityKindMetric to the database.
func (cakm *CuptiActivityKindMetric) Save(db XODB) error {
	if cakm.Exists() {
		return cakm.Update(db)
	}

	return cakm.Insert(db)
}

// Delete deletes the CuptiActivityKindMetric from the database.
func (cakm *CuptiActivityKindMetric) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cakm._exists {
		return nil
	}

	// if deleted, bail
	if cakm._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM CUPTI_ACTIVITY_KIND_METRIC WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cakm.ID)
	_, err = db.Exec(sqlstr, cakm.ID)
	if err != nil {
		return err
	}

	// set deleted
	cakm._deleted = true

	return nil
}

// CuptiActivityKindMetricByID retrieves a row from 'CUPTI_ACTIVITY_KIND_METRIC' as a CuptiActivityKindMetric.
//
// Generated from index 'CUPTI_ACTIVITY_KIND_METRIC__id__pkey'.
func CuptiActivityKindMetricByID(db XODB, id sql.NullInt64) (*CuptiActivityKindMetric, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, id, value, correlationId, flags ` +
		`FROM CUPTI_ACTIVITY_KIND_METRIC ` +
		`WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, id)
	cakm := CuptiActivityKindMetric{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&cakm.ID, &cakm.ID, &cakm.Value, &cakm.Correlationid, &cakm.Flags)
	if err != nil {
		return nil, err
	}

	return &cakm, nil
}

// CuptiActivityKindMetricsByCorrelationid retrieves a row from 'CUPTI_ACTIVITY_KIND_METRIC' as a CuptiActivityKindMetric.
//
// Generated from index 'INDEX_CUPTI_ACTIVITY_KIND_METRIC'.
func CuptiActivityKindMetricsByCorrelationid(db XODB, correlationid int) ([]*CuptiActivityKindMetric, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, id, value, correlationId, flags ` +
		`FROM CUPTI_ACTIVITY_KIND_METRIC ` +
		`WHERE correlationId = ?`

	// run query
	XOLog(sqlstr, correlationid)
	q, err := db.Query(sqlstr, correlationid)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*CuptiActivityKindMetric{}
	for q.Next() {
		cakm := CuptiActivityKindMetric{
			_exists: true,
		}

		// scan
		err = q.Scan(&cakm.ID, &cakm.ID, &cakm.Value, &cakm.Correlationid, &cakm.Flags)
		if err != nil {
			return nil, err
		}

		res = append(res, &cakm)
	}

	return res, nil
}
