// Package models contains the types for schema ''.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
)

// CuptiActivityKindEnvironment represents a row from 'CUPTI_ACTIVITY_KIND_ENVIRONMENT'.
type CuptiActivityKindEnvironment struct {
	ID              sql.NullInt64 `json:"_id_"`            // _id_
	Deviceid        int           `json:"deviceId"`        // deviceId
	Timestamp       int           `json:"timestamp"`       // timestamp
	Environmentkind int           `json:"environmentKind"` // environmentKind
	Data            []byte        `json:"data"`            // data

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the CuptiActivityKindEnvironment exists in the database.
func (cake *CuptiActivityKindEnvironment) Exists() bool {
	return cake._exists
}

// Deleted provides information if the CuptiActivityKindEnvironment has been deleted from the database.
func (cake *CuptiActivityKindEnvironment) Deleted() bool {
	return cake._deleted
}

// Insert inserts the CuptiActivityKindEnvironment to the database.
func (cake *CuptiActivityKindEnvironment) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if cake._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO CUPTI_ACTIVITY_KIND_ENVIRONMENT (` +
		`deviceId, timestamp, environmentKind, data` +
		`) VALUES (` +
		`?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, cake.Deviceid, cake.Timestamp, cake.Environmentkind, cake.Data)
	res, err := db.Exec(sqlstr, cake.Deviceid, cake.Timestamp, cake.Environmentkind, cake.Data)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	cake.ID = sql.NullInt64(id)
	cake._exists = true

	return nil
}

// Update updates the CuptiActivityKindEnvironment in the database.
func (cake *CuptiActivityKindEnvironment) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cake._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if cake._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE CUPTI_ACTIVITY_KIND_ENVIRONMENT SET ` +
		`deviceId = ?, timestamp = ?, environmentKind = ?, data = ?` +
		` WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cake.Deviceid, cake.Timestamp, cake.Environmentkind, cake.Data, cake.ID)
	_, err = db.Exec(sqlstr, cake.Deviceid, cake.Timestamp, cake.Environmentkind, cake.Data, cake.ID)
	return err
}

// Save saves the CuptiActivityKindEnvironment to the database.
func (cake *CuptiActivityKindEnvironment) Save(db XODB) error {
	if cake.Exists() {
		return cake.Update(db)
	}

	return cake.Insert(db)
}

// Delete deletes the CuptiActivityKindEnvironment from the database.
func (cake *CuptiActivityKindEnvironment) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cake._exists {
		return nil
	}

	// if deleted, bail
	if cake._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM CUPTI_ACTIVITY_KIND_ENVIRONMENT WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cake.ID)
	_, err = db.Exec(sqlstr, cake.ID)
	if err != nil {
		return err
	}

	// set deleted
	cake._deleted = true

	return nil
}

// CuptiActivityKindEnvironmentByID retrieves a row from 'CUPTI_ACTIVITY_KIND_ENVIRONMENT' as a CuptiActivityKindEnvironment.
//
// Generated from index 'CUPTI_ACTIVITY_KIND_ENVIRONMENT__id__pkey'.
func CuptiActivityKindEnvironmentByID(db XODB, id sql.NullInt64) (*CuptiActivityKindEnvironment, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, deviceId, timestamp, environmentKind, data ` +
		`FROM CUPTI_ACTIVITY_KIND_ENVIRONMENT ` +
		`WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, id)
	cake := CuptiActivityKindEnvironment{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&cake.ID, &cake.Deviceid, &cake.Timestamp, &cake.Environmentkind, &cake.Data)
	if err != nil {
		return nil, err
	}

	return &cake, nil
}

// CuptiActivityKindEnvironmentsByTimestamp retrieves a row from 'CUPTI_ACTIVITY_KIND_ENVIRONMENT' as a CuptiActivityKindEnvironment.
//
// Generated from index 'INDEX_CUPTI_ACTIVITY_KIND_ENVIRONMENT'.
func CuptiActivityKindEnvironmentsByTimestamp(db XODB, timestamp int) ([]*CuptiActivityKindEnvironment, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, deviceId, timestamp, environmentKind, data ` +
		`FROM CUPTI_ACTIVITY_KIND_ENVIRONMENT ` +
		`WHERE timestamp = ?`

	// run query
	XOLog(sqlstr, timestamp)
	q, err := db.Query(sqlstr, timestamp)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*CuptiActivityKindEnvironment{}
	for q.Next() {
		cake := CuptiActivityKindEnvironment{
			_exists: true,
		}

		// scan
		err = q.Scan(&cake.ID, &cake.Deviceid, &cake.Timestamp, &cake.Environmentkind, &cake.Data)
		if err != nil {
			return nil, err
		}

		res = append(res, &cake)
	}

	return res, nil
}
