// Package models contains the types for schema ''.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
)

// CuptiActivityKindMemcpy2 represents a row from 'CUPTI_ACTIVITY_KIND_MEMCPY2'.
type CuptiActivityKindMemcpy2 struct {
	ID            sql.NullInt64 `json:"_id_"`          // _id_
	Copykind      int           `json:"copyKind"`      // copyKind
	Srckind       int           `json:"srcKind"`       // srcKind
	Dstkind       int           `json:"dstKind"`       // dstKind
	Flags         int           `json:"flags"`         // flags
	Bytes         int           `json:"bytes"`         // bytes
	Start         int           `json:"start"`         // start
	End           int           `json:"end"`           // end
	Deviceid      int           `json:"deviceId"`      // deviceId
	Contextid     int           `json:"contextId"`     // contextId
	Streamid      int           `json:"streamId"`      // streamId
	Srcdeviceid   int           `json:"srcDeviceId"`   // srcDeviceId
	Srccontextid  int           `json:"srcContextId"`  // srcContextId
	Dstdeviceid   int           `json:"dstDeviceId"`   // dstDeviceId
	Dstcontextid  int           `json:"dstContextId"`  // dstContextId
	Correlationid int           `json:"correlationId"` // correlationId

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the CuptiActivityKindMemcpy2 exists in the database.
func (cakm *CuptiActivityKindMemcpy2) Exists() bool {
	return cakm._exists
}

// Deleted provides information if the CuptiActivityKindMemcpy2 has been deleted from the database.
func (cakm *CuptiActivityKindMemcpy2) Deleted() bool {
	return cakm._deleted
}

// Insert inserts the CuptiActivityKindMemcpy2 to the database.
func (cakm *CuptiActivityKindMemcpy2) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if cakm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO CUPTI_ACTIVITY_KIND_MEMCPY2 (` +
		`copyKind, srcKind, dstKind, flags, bytes, start, end, deviceId, contextId, streamId, srcDeviceId, srcContextId, dstDeviceId, dstContextId, correlationId` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, cakm.Copykind, cakm.Srckind, cakm.Dstkind, cakm.Flags, cakm.Bytes, cakm.Start, cakm.End, cakm.Deviceid, cakm.Contextid, cakm.Streamid, cakm.Srcdeviceid, cakm.Srccontextid, cakm.Dstdeviceid, cakm.Dstcontextid, cakm.Correlationid)
	res, err := db.Exec(sqlstr, cakm.Copykind, cakm.Srckind, cakm.Dstkind, cakm.Flags, cakm.Bytes, cakm.Start, cakm.End, cakm.Deviceid, cakm.Contextid, cakm.Streamid, cakm.Srcdeviceid, cakm.Srccontextid, cakm.Dstdeviceid, cakm.Dstcontextid, cakm.Correlationid)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	cakm.ID = sql.NullInt64(id)
	cakm._exists = true

	return nil
}

// Update updates the CuptiActivityKindMemcpy2 in the database.
func (cakm *CuptiActivityKindMemcpy2) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cakm._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if cakm._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE CUPTI_ACTIVITY_KIND_MEMCPY2 SET ` +
		`copyKind = ?, srcKind = ?, dstKind = ?, flags = ?, bytes = ?, start = ?, end = ?, deviceId = ?, contextId = ?, streamId = ?, srcDeviceId = ?, srcContextId = ?, dstDeviceId = ?, dstContextId = ?, correlationId = ?` +
		` WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cakm.Copykind, cakm.Srckind, cakm.Dstkind, cakm.Flags, cakm.Bytes, cakm.Start, cakm.End, cakm.Deviceid, cakm.Contextid, cakm.Streamid, cakm.Srcdeviceid, cakm.Srccontextid, cakm.Dstdeviceid, cakm.Dstcontextid, cakm.Correlationid, cakm.ID)
	_, err = db.Exec(sqlstr, cakm.Copykind, cakm.Srckind, cakm.Dstkind, cakm.Flags, cakm.Bytes, cakm.Start, cakm.End, cakm.Deviceid, cakm.Contextid, cakm.Streamid, cakm.Srcdeviceid, cakm.Srccontextid, cakm.Dstdeviceid, cakm.Dstcontextid, cakm.Correlationid, cakm.ID)
	return err
}

// Save saves the CuptiActivityKindMemcpy2 to the database.
func (cakm *CuptiActivityKindMemcpy2) Save(db XODB) error {
	if cakm.Exists() {
		return cakm.Update(db)
	}

	return cakm.Insert(db)
}

// Delete deletes the CuptiActivityKindMemcpy2 from the database.
func (cakm *CuptiActivityKindMemcpy2) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cakm._exists {
		return nil
	}

	// if deleted, bail
	if cakm._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM CUPTI_ACTIVITY_KIND_MEMCPY2 WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cakm.ID)
	_, err = db.Exec(sqlstr, cakm.ID)
	if err != nil {
		return err
	}

	// set deleted
	cakm._deleted = true

	return nil
}

// CuptiActivityKindMemcpy2ByID retrieves a row from 'CUPTI_ACTIVITY_KIND_MEMCPY2' as a CuptiActivityKindMemcpy2.
//
// Generated from index 'CUPTI_ACTIVITY_KIND_MEMCPY2__id__pkey'.
func CuptiActivityKindMemcpy2ByID(db XODB, id sql.NullInt64) (*CuptiActivityKindMemcpy2, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, copyKind, srcKind, dstKind, flags, bytes, start, end, deviceId, contextId, streamId, srcDeviceId, srcContextId, dstDeviceId, dstContextId, correlationId ` +
		`FROM CUPTI_ACTIVITY_KIND_MEMCPY2 ` +
		`WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, id)
	cakm := CuptiActivityKindMemcpy2{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&cakm.ID, &cakm.Copykind, &cakm.Srckind, &cakm.Dstkind, &cakm.Flags, &cakm.Bytes, &cakm.Start, &cakm.End, &cakm.Deviceid, &cakm.Contextid, &cakm.Streamid, &cakm.Srcdeviceid, &cakm.Srccontextid, &cakm.Dstdeviceid, &cakm.Dstcontextid, &cakm.Correlationid)
	if err != nil {
		return nil, err
	}

	return &cakm, nil
}

// CuptiActivityKindMemcpy2sByCorrelationid retrieves a row from 'CUPTI_ACTIVITY_KIND_MEMCPY2' as a CuptiActivityKindMemcpy2.
//
// Generated from index 'INDEX_CUPTI_ACTIVITY_KIND_MEMCPY2'.
func CuptiActivityKindMemcpy2sByCorrelationid(db XODB, correlationid int) ([]*CuptiActivityKindMemcpy2, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, copyKind, srcKind, dstKind, flags, bytes, start, end, deviceId, contextId, streamId, srcDeviceId, srcContextId, dstDeviceId, dstContextId, correlationId ` +
		`FROM CUPTI_ACTIVITY_KIND_MEMCPY2 ` +
		`WHERE correlationId = ?`

	// run query
	XOLog(sqlstr, correlationid)
	q, err := db.Query(sqlstr, correlationid)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*CuptiActivityKindMemcpy2{}
	for q.Next() {
		cakm := CuptiActivityKindMemcpy2{
			_exists: true,
		}

		// scan
		err = q.Scan(&cakm.ID, &cakm.Copykind, &cakm.Srckind, &cakm.Dstkind, &cakm.Flags, &cakm.Bytes, &cakm.Start, &cakm.End, &cakm.Deviceid, &cakm.Contextid, &cakm.Streamid, &cakm.Srcdeviceid, &cakm.Srccontextid, &cakm.Dstdeviceid, &cakm.Dstcontextid, &cakm.Correlationid)
		if err != nil {
			return nil, err
		}

		res = append(res, &cakm)
	}

	return res, nil
}
