// Package models contains the types for schema ''.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
)

// CuptiActivityKindOpenaccDatum represents a row from 'CUPTI_ACTIVITY_KIND_OPENACC_DATA'.
type CuptiActivityKindOpenaccDatum struct {
	ID              sql.NullInt64 `json:"_id_"`            // _id_
	Eventkind       int           `json:"eventKind"`       // eventKind
	Parentconstruct int           `json:"parentConstruct"` // parentConstruct
	Version         int           `json:"version"`         // version
	Implicit        int           `json:"implicit"`        // implicit
	Devicetype      int           `json:"deviceType"`      // deviceType
	Devicenumber    int           `json:"deviceNumber"`    // deviceNumber
	Threadid        int           `json:"threadId"`        // threadId
	Async           int           `json:"async"`           // async
	Asyncmap        int           `json:"asyncMap"`        // asyncMap
	Lineno          int           `json:"lineNo"`          // lineNo
	Endlineno       int           `json:"endLineNo"`       // endLineNo
	Funclineno      int           `json:"funcLineNo"`      // funcLineNo
	Funcendlineno   int           `json:"funcEndLineNo"`   // funcEndLineNo
	Start           int           `json:"start"`           // start
	End             int           `json:"end"`             // end
	Cudeviceid      int           `json:"cuDeviceId"`      // cuDeviceId
	Cucontextid     int           `json:"cuContextId"`     // cuContextId
	Custreamid      int           `json:"cuStreamId"`      // cuStreamId
	Cuprocessid     int           `json:"cuProcessId"`     // cuProcessId
	Cuthreadid      int           `json:"cuThreadId"`      // cuThreadId
	Externalid      int           `json:"externalId"`      // externalId
	Srcfile         int           `json:"srcFile"`         // srcFile
	Funcname        int           `json:"funcName"`        // funcName
	Bytes           int           `json:"bytes"`           // bytes
	Hostptr         int           `json:"hostPtr"`         // hostPtr
	Deviceptr       int           `json:"devicePtr"`       // devicePtr
	Varname         int           `json:"varName"`         // varName

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the CuptiActivityKindOpenaccDatum exists in the database.
func (cakod *CuptiActivityKindOpenaccDatum) Exists() bool {
	return cakod._exists
}

// Deleted provides information if the CuptiActivityKindOpenaccDatum has been deleted from the database.
func (cakod *CuptiActivityKindOpenaccDatum) Deleted() bool {
	return cakod._deleted
}

// Insert inserts the CuptiActivityKindOpenaccDatum to the database.
func (cakod *CuptiActivityKindOpenaccDatum) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if cakod._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO CUPTI_ACTIVITY_KIND_OPENACC_DATA (` +
		`eventKind, parentConstruct, version, implicit, deviceType, deviceNumber, threadId, async, asyncMap, lineNo, endLineNo, funcLineNo, funcEndLineNo, start, end, cuDeviceId, cuContextId, cuStreamId, cuProcessId, cuThreadId, externalId, srcFile, funcName, bytes, hostPtr, devicePtr, varName` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, cakod.Eventkind, cakod.Parentconstruct, cakod.Version, cakod.Implicit, cakod.Devicetype, cakod.Devicenumber, cakod.Threadid, cakod.Async, cakod.Asyncmap, cakod.Lineno, cakod.Endlineno, cakod.Funclineno, cakod.Funcendlineno, cakod.Start, cakod.End, cakod.Cudeviceid, cakod.Cucontextid, cakod.Custreamid, cakod.Cuprocessid, cakod.Cuthreadid, cakod.Externalid, cakod.Srcfile, cakod.Funcname, cakod.Bytes, cakod.Hostptr, cakod.Deviceptr, cakod.Varname)
	res, err := db.Exec(sqlstr, cakod.Eventkind, cakod.Parentconstruct, cakod.Version, cakod.Implicit, cakod.Devicetype, cakod.Devicenumber, cakod.Threadid, cakod.Async, cakod.Asyncmap, cakod.Lineno, cakod.Endlineno, cakod.Funclineno, cakod.Funcendlineno, cakod.Start, cakod.End, cakod.Cudeviceid, cakod.Cucontextid, cakod.Custreamid, cakod.Cuprocessid, cakod.Cuthreadid, cakod.Externalid, cakod.Srcfile, cakod.Funcname, cakod.Bytes, cakod.Hostptr, cakod.Deviceptr, cakod.Varname)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	cakod.ID = sql.NullInt64(id)
	cakod._exists = true

	return nil
}

// Update updates the CuptiActivityKindOpenaccDatum in the database.
func (cakod *CuptiActivityKindOpenaccDatum) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cakod._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if cakod._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE CUPTI_ACTIVITY_KIND_OPENACC_DATA SET ` +
		`eventKind = ?, parentConstruct = ?, version = ?, implicit = ?, deviceType = ?, deviceNumber = ?, threadId = ?, async = ?, asyncMap = ?, lineNo = ?, endLineNo = ?, funcLineNo = ?, funcEndLineNo = ?, start = ?, end = ?, cuDeviceId = ?, cuContextId = ?, cuStreamId = ?, cuProcessId = ?, cuThreadId = ?, externalId = ?, srcFile = ?, funcName = ?, bytes = ?, hostPtr = ?, devicePtr = ?, varName = ?` +
		` WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cakod.Eventkind, cakod.Parentconstruct, cakod.Version, cakod.Implicit, cakod.Devicetype, cakod.Devicenumber, cakod.Threadid, cakod.Async, cakod.Asyncmap, cakod.Lineno, cakod.Endlineno, cakod.Funclineno, cakod.Funcendlineno, cakod.Start, cakod.End, cakod.Cudeviceid, cakod.Cucontextid, cakod.Custreamid, cakod.Cuprocessid, cakod.Cuthreadid, cakod.Externalid, cakod.Srcfile, cakod.Funcname, cakod.Bytes, cakod.Hostptr, cakod.Deviceptr, cakod.Varname, cakod.ID)
	_, err = db.Exec(sqlstr, cakod.Eventkind, cakod.Parentconstruct, cakod.Version, cakod.Implicit, cakod.Devicetype, cakod.Devicenumber, cakod.Threadid, cakod.Async, cakod.Asyncmap, cakod.Lineno, cakod.Endlineno, cakod.Funclineno, cakod.Funcendlineno, cakod.Start, cakod.End, cakod.Cudeviceid, cakod.Cucontextid, cakod.Custreamid, cakod.Cuprocessid, cakod.Cuthreadid, cakod.Externalid, cakod.Srcfile, cakod.Funcname, cakod.Bytes, cakod.Hostptr, cakod.Deviceptr, cakod.Varname, cakod.ID)
	return err
}

// Save saves the CuptiActivityKindOpenaccDatum to the database.
func (cakod *CuptiActivityKindOpenaccDatum) Save(db XODB) error {
	if cakod.Exists() {
		return cakod.Update(db)
	}

	return cakod.Insert(db)
}

// Delete deletes the CuptiActivityKindOpenaccDatum from the database.
func (cakod *CuptiActivityKindOpenaccDatum) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !cakod._exists {
		return nil
	}

	// if deleted, bail
	if cakod._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM CUPTI_ACTIVITY_KIND_OPENACC_DATA WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, cakod.ID)
	_, err = db.Exec(sqlstr, cakod.ID)
	if err != nil {
		return err
	}

	// set deleted
	cakod._deleted = true

	return nil
}

// CuptiActivityKindOpenaccDatumByID retrieves a row from 'CUPTI_ACTIVITY_KIND_OPENACC_DATA' as a CuptiActivityKindOpenaccDatum.
//
// Generated from index 'CUPTI_ACTIVITY_KIND_OPENACC_DATA__id__pkey'.
func CuptiActivityKindOpenaccDatumByID(db XODB, id sql.NullInt64) (*CuptiActivityKindOpenaccDatum, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, eventKind, parentConstruct, version, implicit, deviceType, deviceNumber, threadId, async, asyncMap, lineNo, endLineNo, funcLineNo, funcEndLineNo, start, end, cuDeviceId, cuContextId, cuStreamId, cuProcessId, cuThreadId, externalId, srcFile, funcName, bytes, hostPtr, devicePtr, varName ` +
		`FROM CUPTI_ACTIVITY_KIND_OPENACC_DATA ` +
		`WHERE _id_ = ?`

	// run query
	XOLog(sqlstr, id)
	cakod := CuptiActivityKindOpenaccDatum{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&cakod.ID, &cakod.Eventkind, &cakod.Parentconstruct, &cakod.Version, &cakod.Implicit, &cakod.Devicetype, &cakod.Devicenumber, &cakod.Threadid, &cakod.Async, &cakod.Asyncmap, &cakod.Lineno, &cakod.Endlineno, &cakod.Funclineno, &cakod.Funcendlineno, &cakod.Start, &cakod.End, &cakod.Cudeviceid, &cakod.Cucontextid, &cakod.Custreamid, &cakod.Cuprocessid, &cakod.Cuthreadid, &cakod.Externalid, &cakod.Srcfile, &cakod.Funcname, &cakod.Bytes, &cakod.Hostptr, &cakod.Deviceptr, &cakod.Varname)
	if err != nil {
		return nil, err
	}

	return &cakod, nil
}

// CuptiActivityKindOpenaccDataByStart retrieves a row from 'CUPTI_ACTIVITY_KIND_OPENACC_DATA' as a CuptiActivityKindOpenaccDatum.
//
// Generated from index 'INDEX_CUPTI_ACTIVITY_KIND_OPENACC_DATA'.
func CuptiActivityKindOpenaccDataByStart(db XODB, start int) ([]*CuptiActivityKindOpenaccDatum, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`_id_, eventKind, parentConstruct, version, implicit, deviceType, deviceNumber, threadId, async, asyncMap, lineNo, endLineNo, funcLineNo, funcEndLineNo, start, end, cuDeviceId, cuContextId, cuStreamId, cuProcessId, cuThreadId, externalId, srcFile, funcName, bytes, hostPtr, devicePtr, varName ` +
		`FROM CUPTI_ACTIVITY_KIND_OPENACC_DATA ` +
		`WHERE start = ?`

	// run query
	XOLog(sqlstr, start)
	q, err := db.Query(sqlstr, start)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*CuptiActivityKindOpenaccDatum{}
	for q.Next() {
		cakod := CuptiActivityKindOpenaccDatum{
			_exists: true,
		}

		// scan
		err = q.Scan(&cakod.ID, &cakod.Eventkind, &cakod.Parentconstruct, &cakod.Version, &cakod.Implicit, &cakod.Devicetype, &cakod.Devicenumber, &cakod.Threadid, &cakod.Async, &cakod.Asyncmap, &cakod.Lineno, &cakod.Endlineno, &cakod.Funclineno, &cakod.Funcendlineno, &cakod.Start, &cakod.End, &cakod.Cudeviceid, &cakod.Cucontextid, &cakod.Custreamid, &cakod.Cuprocessid, &cakod.Cuthreadid, &cakod.Externalid, &cakod.Srcfile, &cakod.Funcname, &cakod.Bytes, &cakod.Hostptr, &cakod.Deviceptr, &cakod.Varname)
		if err != nil {
			return nil, err
		}

		res = append(res, &cakod)
	}

	return res, nil
}
